1. Update demo.py and cases in demo 2. Add OpenXlab link in readme 3. update inference
open-mmlab/FoleyCrafter pull request #3
Opened 2024-07-04 13:01 UTC by ymzhang0319

2024-07-04 14:20 UTC, zengyh1900 requested changes

2024-07-04 14:20 UTC, zengyh1900 commented on app.py
> +from foleycrafter.pipelines.auffusion_pipeline import denormalize_spectrogram
have you ever use pre-commit to check the lint issue?

2024-07-04 14:20 UTC, zengyh1900 commented on app.py
> +parser.add_argument("--share", type=bool, default=True)
I think the default value shouldn't be True. Most users may run it locally.

2024-07-04 14:20 UTC, zengyh1900 commented on app.py
> +            pretrained_model_name_or_path = snapshot_download(pretrained_model_name_or_path, local_dir='models/auffusion')
for `local_dir` which is used to save checkpoints, using `checkpoints` instead of `models` would be better.

2024-07-04 14:20 UTC, zengyh1900 commented on app.py
> +        fc_ckpt = 'ymzhang319/FoleyCrafter'
personal info?

2024-07-04 14:20 UTC, zengyh1900 commented on app.py
> +            fc_ckpt = snapshot_download(fc_ckpt, local_dir='models/')
check the directory path

2024-07-04 14:20 UTC, zengyh1900 commented on assets/input/case1.mp4
put these examples under `examples`

2024-07-04 14:20 UTC, zengyh1900 commented on inference.py
> +    config.add_argument('--temporal_align', type=bool, default=True, help='use temporal adapter or not')
we should use two types of scale instead of a boolean type for temporal alignment

2024-07-05 02:44 UTC, ymzhang0319 commented on app.py
> +from foleycrafter.pipelines.auffusion_pipeline import denormalize_spectrogram
Sorry, i'll remember it.

2024-07-05 02:44 UTC, ymzhang0319 commented on app.py
> +        fc_ckpt = 'ymzhang319/FoleyCrafter'
Huggingface repo name.

2024-07-05 07:20 UTC, zengyh1900 requested changes

2024-07-05 07:20 UTC, zengyh1900 commented on inference.py
> +        fc_ckpt = snapshot_download(fc_ckpt, local_dir="checkpoints/")
I think you should use `args.ckpt` ?

2024-07-05 07:20 UTC, zengyh1900 commented on inference.py
> +        "./checkpoints/semantic", subfolder="", weight_name="semantic_adapter.bin", image_encoder_folder=None
`args.ckpt`?

2024-07-05 07:21 UTC, zengyh1900 requested changes

2024-07-05 07:21 UTC, zengyh1900 commented on app.py
> +        self.model_dir = os.path.join(self.basedir, "checkpoints")
I think it would be better to add another argument in `parser` for `checkpoints` instead of hard code here.

2024-07-05 09:16 UTC, zengyh1900 approved these changes
lgtm

2024-07-05 09:17 UTC, merged